version: "3.8"

services:
  dash-app:
    build: .
    ports:
      - "8050:8050"
    volumes:
      - .:/app
    environment:
      - PORT=8050
    networks:
      - dash-network

networks:
  dash-network:
    driver: bridge
